name: Deploy Golem

on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: zgamelogic/github-actions/.github/workflows/kubernetes-deploy.yaml@0.0.1
    with:
      environment: production
      deploymentName: golem
      imageName: golem